title: Xu Yu-Chia's Blog
description: 分享程式、專案與生活！
baseurl: "/blog"  
url: "https://xu-yu-chia.github.io"
theme: minima
markdown: kramdown

kramdown:
  input: GFM   # 啟用 GitHub Flavored Markdown，增加語法相容性
  #parse_block_html: true     # ← 讓 HTML 區塊內的 Markdown 也會被解析（縮排/清單不會消失）
  hard_wrap: true
  math_engine: mathjax
  syntax_highlighter: rouge
  toc_levels: 2..4  # 設定要顯示的標題層級 (H2 ~ H4)

collections:
  tags:
    output: true
    permalink: /tags/:name/


permalink: /:year/:month/:day/:title/


